"""baseline schema (pre-pivot)

Revision ID: e8d2efaa80d1
Revises: 
Create Date: 2026-05-09 17:18:30.497350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d2efaa80d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('twitter_id', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('annual_revenue', sa.String(length=50), nullable=True),
    sa.Column('marketing_budget', sa.String(length=50), nullable=True),
    sa.Column('primary_marketing_channels', sa.Text(), nullable=True),
    sa.Column('marketing_goals', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('biggest_marketing_challenge', sa.Text(), nullable=True),
    sa.Column('how_heard_about_us', sa.String(length=100), nullable=True),
    sa.Column('email_marketing_consent', sa.Boolean(), nullable=True),
    sa.Column('sms_marketing_consent', sa.Boolean(), nullable=True),
    sa.Column('newsletter_subscription', sa.Boolean(), nullable=True),
    sa.Column('product_updates_consent', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('profile_completion_percentage', sa.Integer(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('BASIC', 'PLUS', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=True),
    sa.Column('subscription_expires', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('coupon_used', sa.String(length=100), nullable=True),
    sa.Column('trial_expires', sa.DateTime(), nullable=True),
    sa.Column('lifetime_access', sa.Boolean(), nullable=True),
    sa.Column('generations_used_this_month', sa.Integer(), nullable=True),
    sa.Column('generations_used_today', sa.Integer(), nullable=True),
    sa.Column('last_generation_date', sa.Date(), nullable=True),
    sa.Column('billing_period_start', sa.DateTime(), nullable=True),
    sa.Column('account_on_hold', sa.Boolean(), nullable=True),
    sa.Column('hold_start_date', sa.DateTime(), nullable=True),
    sa.Column('hold_end_date', sa.DateTime(), nullable=True),
    sa.Column('last_hold_year', sa.Integer(), nullable=True),
    sa.Column('payment_failed_date', sa.DateTime(), nullable=True),
    sa.Column('account_deletion_date', sa.DateTime(), nullable=True),
    sa.Column('account_active', sa.Boolean(), nullable=True),
    sa.Column('is_demo_account', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('business_document_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('twitter_id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('subscription_tier', sa.Enum('BASIC', 'PLUS', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=True),
    sa.Column('subscription_expires', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('business_url', sa.String(length=500), nullable=True),
    sa.Column('target_audience', sa.String(length=200), nullable=True),
    sa.Column('campaign_goal', sa.String(length=100), nullable=True),
    sa.Column('brand_voice', sa.String(length=100), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('analysis_data', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('business_metadata', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('differentiators', sa.JSON(), nullable=True),
    sa.Column('marketing_theme', sa.Text(), nullable=True),
    sa.Column('ad_text', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('video_prompt', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ai_content', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('tier_used', sa.String(length=20), nullable=True),
    sa.Column('services_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('auto_post_enabled', sa.Boolean(), nullable=True),
    sa.Column('next_post_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('ad_strategies', sa.JSON(), nullable=True),
    sa.Column('is_ai_detected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_user_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires', sa.DateTime(), nullable=True),
    sa.Column('auto_post_enabled', sa.Boolean(), nullable=True),
    sa.Column('post_frequency_hours', sa.Integer(), nullable=True),
    sa.Column('vary_content', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('check_results', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('regeneration_attempt', sa.Integer(), nullable=True),
    sa.Column('coherent_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('relevant_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('compelling_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('fresh_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('unique_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('creative_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('edgy_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('worth_paying_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('failed_criteria', sa.JSON(), nullable=True),
    sa.Column('specific_issues', sa.JSON(), nullable=True),
    sa.Column('improvement_recommendations', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_post_id', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('post_frequency', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('next_post_time', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('geo_location', sa.String(length=10), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('data_sources', sa.Text(), nullable=True),
    sa.Column('business_intelligence', sa.Text(), nullable=True),
    sa.Column('competitor_analysis', sa.Text(), nullable=True),
    sa.Column('trend_analysis', sa.Text(), nullable=True),
    sa.Column('content_opportunities', sa.Text(), nullable=True),
    sa.Column('scraping_successful', sa.Boolean(), nullable=True),
    sa.Column('fallback_protocols_used', sa.Boolean(), nullable=True),
    sa.Column('metadata_extracted', sa.Boolean(), nullable=True),
    sa.Column('update_history', sa.Text(), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_analyses')
    op.drop_table('social_posts')
    op.drop_table('quality_checks')
    op.drop_table('social_accounts')
    op.drop_table('competitors')
    op.drop_table('campaigns')
    op.drop_table('brands')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
