"""pivot to internal salesperson tool

Adds the columns required to flip Dominate Marketing from B2C SaaS into an
internal tool used by Fred's salespeople to manage client marketing campaigns:

  - User.is_salesperson, User.is_admin, User.created_by_admin_id
  - User.email is relaxed to nullable (admin-created accounts skip OAuth)
  - Brand gains client-management contact fields, status, retainer, notes

The schema is purely additive: no existing data is rewritten and no columns
are dropped. The downgrade reverses everything (used only for local dev).

NOTE: Three small adjustments were made to the autogenerated output before
committing — these are flagged inline with `# MANUAL FIX` comments:
  1. is_salesperson / is_admin / brands.status NOT NULL columns get a
     server_default so existing rows don't reject the migration.
  2. The created_by_admin_id foreign key is given an explicit name
     (Postgres requires it; Alembic's autogen leaves it as None).
  3. The is_salesperson / is_admin server_default is dropped after backfill
     so the application layer (not the database) owns the default going
     forward — matches how the other Boolean columns in this schema behave.

Revision ID: f06038cdd1a2
Revises: e8d2efaa80d1
Create Date: 2026-05-09 17:19:58.036488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06038cdd1a2'
down_revision = 'e8d2efaa80d1'
branch_labels = None
depends_on = None


def upgrade():
    # --- brands: client-management fields --------------------------------
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('billing_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('monthly_retainer', sa.Numeric(precision=10, scale=2), nullable=True))
        # MANUAL FIX (2): server_default='active' so existing brand rows
        # backfill cleanly when this migration runs against prod.
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('onboarded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # --- users: salesperson / admin role columns -------------------------
    with op.batch_alter_table('users', schema=None) as batch_op:
        # MANUAL FIX (1): server_default=sa.false() so existing user rows
        # backfill to False when the NOT NULL column is added. Without this
        # the migration would crash on any non-empty users table.
        batch_op.add_column(sa.Column('is_salesperson', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('created_by_admin_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        # MANUAL FIX (3): explicit FK constraint name. Alembic's autogen
        # emits None which Postgres rejects on subsequent drops.
        batch_op.create_foreign_key(
            'fk_users_created_by_admin_id',
            'users',
            ['created_by_admin_id'],
            ['id'],
        )

    # MANUAL FIX (1, part 2): drop the server_default from is_salesperson and
    # is_admin now that existing rows are backfilled. Going forward the
    # application layer (Python default=False on the column definition) owns
    # the default — matches how the other Boolean columns in this schema work.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_salesperson', server_default=None)
        batch_op.alter_column('is_admin', server_default=None)


def downgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_created_by_admin_id', type_='foreignkey')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('created_by_admin_id')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_salesperson')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('onboarded_at')
        batch_op.drop_column('status')
        batch_op.drop_column('monthly_retainer')
        batch_op.drop_column('billing_notes')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_name')
